=== solyd/nihul5/WebContent/WEB-INF/app306932039.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT app306932039 (event*, post*)>
<!ELEMENT event (username, lat, lng, creation_date, title, content, event_date, capacity, num_of_registered, registered_users, consensus_reqs)>
<!ELEMENT post (username, lat, lng, creation_date, title, content)>
<!ATTLIST event
	id CDATA #REQUIRED>
<!ATTLIST post
	id CDATA #REQUIRED>
<!ELEMENT username (#PCDATA)>
<!ELEMENT lat (#PCDATA)>
<!ELEMENT lng (#PCDATA)>
<!ELEMENT creation_date (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT event_date (#PCDATA)>
<!ELEMENT capacity (#PCDATA)>
<!ELEMENT num_of_registered (#PCDATA)>
<!ELEMENT registered_users (username*)>
<!ELEMENT consensus_reqs (consensus*)>
<!ELEMENT consensus (description, status, votes_for_change)>
<!ATTLIST consensus
	id CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT votes_for_change (#PCDATA)>

=== solyd/nihul5/WebContent/WEB-INF/test.xml
<?XMLversion ="1.0" encoding="UTF-8â€œ standalone="no"?>
<!DOCTYPE app306932039 SYSTEM "app306932039.dtd">
<!-- File name: test.xml -->
<app306932039>
    <event id="21">
        <username>sol</username>
        <lat>32.2</lat>
        <lng>1.22</lng>
        <creation_date>129847122</creation_date>
        <title>Something</title>
        <content>this is the content of the message</content>
   
        <event_date>1982749102</event_date>
        <capacity>142</capacity>
       
        <registered_users>
            <username>blabla</username>
            <username>wat</username>
        </registered_users>

        <consensus_reqs>
            <consensus id="21">
                <description>this is consensus req desc</description>
                <status>NOT_ACCEPTED</status>

            <votes_for_change>2</votes_for_change>
            </consensus>  
            <consensus id="22">
                <description>this is consensus req desc</description>
                <status>NOT_ACCEPTED</status>

            <votes_for_change>2</votes_for_change>
            </consensus>      
            
        </consensus_reqs>
    </event>

    <post id="21">
       <username>sol</username>
        <lat>32.2</lat>
        <lng>1.22</lng>
        <creation_date>129847122</creation_date>
        <title>Something</title>
        <content>this is the content of the message</content>
    </post>

</app306932039>
